### ISSUE TITLE
It requires verification code(OTP) everytime

### ISSUE THREAD

**Issue by studio-nuages** [shibe97/worc#37]
I'm using twitter with two-factor authentication, so worc requires verification code everytime I start this application. Is there any way to save the code or skip this step?

**Comment by shibe97** [comment]
Sorry, we can't save code for now.
I’ll consider it.

**Comment by shibe97** [comment]
@studio-nuages
I fixed this issue on this release.
https://github.com/shibe97/worc/releases/tag/v1.8.0

Please Try it.

**Comment by studio-nuages** [comment]
Thank you for fixing the issue.
It works properly.

**Comment by shibe97** [comment]
@studio-nuages Thanks for confirming!
